version: '3'

services:
  db:
    container_name: db
    restart: always
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    networks:
      - api-backend
    
  api_monitoria:
    container_name: api-monitoria
    depends_on:
      - db
    build: .
    command: sh run-django.sh
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    entrypoint: ./wait-for-postgres.sh postgres 5433
    networks:
      - api-backend

networks:
  api-backend:
    external:
      name: api-backend    