# Generated by Django 2.2 on 2019-04-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('user_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=250)),
                ('course', models.CharField(choices=[('SOFTWARE', 'Engenharia de Software'), ('ELETRONICA', 'Engenharia Eletronica'), ('ENERGIA', 'Engenharia de Energia'), ('AERO', 'Engenharia Aeroespacial'), ('AUTOMOTIVA', 'Engenharia Automotiva'), ('ENGENHARIAS', 'Engenharias')], max_length=11)),
                ('deion', models.CharField(max_length=500)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('account_state', models.BooleanField(default=True)),
            ],
        ),
    ]
