# Generated by Django 2.2 on 2019-04-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id_monitoring', models.AutoField(default='', primary_key=True, serialize=False)),
                ('name_monitoring', models.CharField(max_length=150)),
                ('matter', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=500)),
                ('status_monitoring', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
